.TH LINXGWS 1 "2009-02-24" 1.0 "LINX"
.SH NAME
linxgws \- start the LINX Gateway Server
.SH SYNOPSIS
.B linxgws
.RI [ CONFIG
.IR FILE ]
.br
.B linxgws
.I OPTION
.SH DESCRIPTION
.\" Add any additional description here
If no 
.I CONFIG FILE
is given on the command line, then linxgws tries to locate a configuration file
in /etc/linxgws.conf
.PP

.TP
.BR \-\-h | \-\-help
display this help and exit
.TP
.B \-\-version
output version information and exit
.TP
.B The LINX Gateway Server will use the LINX kernel module loaded when clients connect.
.TP
.B The logging is assured via syslog check /var/log/messages /var/log/syslog and /var/log/user depending of your Linux distribution.

.SH AUTHOR
Enea LINX team

.SH REPORTING BUGS
Report bugs to <linx@enea.com>.

.SH EXAMPLES
.nf
linxgws /path/to/my/config/file.conf
.fi

.SH FILES
/etc/linxgws.conf

.SH "SEE ALSO"
.BR linxgws.conf "(5), "
.BR linxgwcmd "(1)"

.SH AUTHOR
Enea LINX team

.SH COPYRIGHT
Copyright (c) 2009, Enea Software AB
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
Neither the name of Enea Software AB nor the names of its
contributors may be used to endorse or promote products derived from this
software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
