.TH LINX_SENDER 3 "2006-09-01" 1.0 "LIBLINX"
.SH NAME
linx_sender() - Retrieve the sender of a LINX signal
.SH SYNOPSIS
.B #include <linx_types.h>
.br
.B #include <linx.h>
.br

.BI "LINX_SPID linx_sender(LINX *" linx ", union LINX_SIGNAL **" sig ");"
.SH DESCRIPTION
Get the binary identifier (spid) of the LINX endpoint which sent the signal
.IR sig "."
.br

.I linx
is the handle of the LINX endpoint on which
.IR sig
was received.
.br

If
.I sig
is corrupt,
.BR abort "(3)"
is called.

.SH "RETURN VALUE"
The identifier (spid) of the LINX endpoint, which sent the signal
.IR sig "."
If the signal was never sent, 
.BR linx_sender "()"
will return the spid of the own LINX endpoint.

.SH "BUGS/LIMITATIONS"
None.
.SH SEE ALSO
.BR linx "(7), " linx_alloc "(3), " linx_receive "(3), " 
.BR linx_receive_from "(3), " linx_receive_w_tmo "(3), " 
.SH AUTHOR
Enea LINX team
.SH COPYRIGHT

Copyright (c) 2006-2007, Enea Software AB
All rights reserved.
.br

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
.br

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
Neither the name of Enea Software AB nor the names of its
contributors may be used to endorse or promote products derived from this
software without specific prior written permission.
.br

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
