.TH LINX_ALLOC 3 "2006-07-30" 1.0 "LIBLINX"
.SH NAME
linx_alloc() - Allocate a signal buffer on a LINX endpoint
.SH SYNOPSIS
.B #include <linx_types.h>
.br
.B #include <linx.h>
.br

.BI "union LINX_SIGNAL *linx_alloc(LINX *" linx ", LINX_OSBUFSIZE " size ", LINX_SIGSELECT "  sig_no ");"
.SH DESCRIPTION
.BR linx_alloc "()"
is used to allocate a signal buffer of the indicated size The first 4 bytes
of the signal buffer are initialized with the provided signal number
.IR sig_no "." 
The signal number can be replaced later by writing a new value in
the first 4 bytes of the buffer.
.br

The new buffer is owned by the LINX endpoint with which it was created. The ownership
is transferred to the receiving LINX endpoint when the signal is successfully sent using
.BR linx_send (3).
If the signal
is not sent, the owner must free the buffer by calling
.BR linx_free_buf (3)
using the same
.BI linx
handle.  The buffer will be freed if the owning LINX endpoint is closed or 
the process owning the endpoint exits.
.br

.I linx
is the handle to the LINX endpoint.
.br

.I size
is the size in bytes of the new signal buffer. The
minimum size is 4 bytes, needed to store the signal number.
.br

.I sig_no
is the signal number stored at the beginning of the signal buffer.

.SH "RETURN VALUE"
On success, a pointer to the allocated signal buffer is returned.
On error, 
LINX_NIL is 
returned and
.I errno 
will be set.
.SH ERRORS

.B EMSGSIZE
The
.I size
is invalid.
.br

.B ENOMEM
Insufficient memory is available.
.SH "BUGS/LIMITATIONS"
None.

.SH NOTES
A LINX signal can be only be sent by the LINX endpoint that owns it, i.e. 
the endpoint it was created from or received on. It can not be reused and sent
by another LINX endpoint.
.br

If a process, which has allocated signal buffers, calls
.IR fork(2),
both instances will own
copies of the signal buffers. As only one process may use a LINX endpoint and 
its resources, either the parent or the child MUST close the LINX endpoint
using
.BR linx_close "(3)."

.SH SEE ALSO
.BR linx "(7), " linx_close "(3), " linx_free_buf "(3), " linx_hunt "(3), " linx_send "(3), " fork "(2)"
.SH AUTHOR
Enea LINX team
.SH COPYRIGHT

Copyright (c) 2006-2007, Enea Software AB
All rights reserved.
.br

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
.br

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
Neither the name of Enea Software AB nor the names of its
contributors may be used to endorse or promote products derived from this
software without specific prior written permission.
.br

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
